# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPriceForEuropeanUpAndInPut <- function(nInt, Strike, Spot, Vol, Rfr, Expiry, br, nReps = 1000L) {
    .Call(`_UpInPutEurOption_getPriceForEuropeanUpAndInPut`, nInt, Strike, Spot, Vol, Rfr, Expiry, br, nReps)
}

rcpp_hello <- function() {
    .Call(`_UpInPutEurOption_rcpp_hello`)
}

